AppBundle_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Default:index }
    requirements:
        _method:  GET


AppBundle_blog_show:
    pattern:  /blog/{slug}
    defaults: { _controller: AppBundle:Default:blog }
    requirements:
        _method:  GET
        id: \d+

AppBundle_admin:
    pattern:  /admin/
    defaults: { _controller: AppBundle:Default:admin }
    requirements:
        _method:  GET